### ISSUE TITLE
"Toggle Hand" doesn't work

### ISSUE THREAD

**Issue by FigoFlash123** [ChrisRegado/streamdeck-googlemeet#17]
Hi

When i'm trying to toggle the hand, from my stream deck, it won't toggle.
The mic and cam toggle perfectly

-FigoFlash123 😊

**Comment by ChrisRegado** [comment]
Is your Google Account language set to something other than English or German? You might be seeing issue https://github.com/ChrisRegado/streamdeck-googlemeet/issues/7.

**Comment by FigoFlash123** [comment]
It's set to danish. But i can't change it, because it's my school account. Which my school host, and have blocked some settings. 

And switching language is one of them... 

Sad for me😞

**Comment by ChrisRegado** [comment]
Yeah, sorry. I'm hoping to take another look at https://github.com/ChrisRegado/streamdeck-googlemeet/issues/7 once the upcoming Google Meet UI refresh is live for everyone. That change might make it easier to support the Hand button in a language-independent way. In the mean time, that's the Issue to watch for updates.
