### ISSUE TITLE
How move or unistall to reinstall?

### ISSUE THREAD

**Issue by garrymansfield** [ChrisRegado/streamdeck-googlemeet#19]
I added to the desktop and this means the plugin file is on there permanently. Then the mic toggle stopped working and said "disconnected"

I wanted to just move but it is in operation so won't let me. Similarly, I cannot uninstall to be able to reinstall in a subfolder?

I tried to uninstall in the streamdeck decktop app but there is no apparent "uninstall" button or option. 

Any ideas?

**Comment by ChrisRegado** [comment]
There seems to be a long-standing bug in the Elgato software that locks the plugin installer file after installing. (The same thing happens with other plugins too.) Quit the Streamdeck software by right clicking it in the Windows task tray or Mac menu bar, click Quit, and then launch the Streamdeck app again. The installer should then be deletable. Or just restart your computer and delete it afterwards.

To uninstall a Streamdeck plugin: from the Streamdeck management app on your PC (v5.0 and newer), right click on one of the Google Meet actions in the list on the right-hand side of the app and click Uninstall.

![Screenshot](https://user-images.githubusercontent.com/1444732/125137491-c5259900-e0da-11eb-940a-7c0c0e9d7f97.png)
