### ISSUE TITLE
Chrome extension manifest version missin

### ISSUE THREAD

**Issue by sc4ttys** [ChrisRegado/streamdeck-googlemeet#26]
Cannot install chrome extension without manifest version [per manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/)

In `manifest.json`, this
`  "manifest_version": 3,`
should be between opening bracket and "name"

**Comment by ChrisRegado** [comment]
What version of Chrome are you running? I'm unable to reproduce any similar errors on current `master` (1e46d9d493e934a2fb27c9b1c6730084354f235b).

**Comment by sc4ttys** [comment]
Version 102.0.5005.61 (Official Build) (x86_64) 
![image](https://user-images.githubusercontent.com/8029013/172327731-5ce8316a-6e9b-4368-a490-b96494e81faa.png)

**Comment by ChrisRegado** [comment]
Are you opening the root of the repository, or the `browser-extension` folder? It needs to be the latter. I'd expect that file path to be `~/Downloads/streamdeck-googlemeet-master/browser-extension`.

**Comment by sc4ttys** [comment]
Oh, oh no, sorry about that! I totally opened the wrong folder. Thanks!
