### ISSUE TITLE
Create release from latest source code

### ISSUE THREAD

**Issue by mgarces** [ChrisRegado/streamdeck-googlemeet#27]
Hi there, 
I've downloaded source code on releases, and I was able to install StreamDeck plugin and also Google Chrome extension, but extension had some warnings regarding manifest V3. 
I've fixed those locally and I was good to go. 

When I check the actual latest code, those changes are already there, but not in the releases tab. 

Can we automate the releases or at least, manually create one, so it includes the latest changes? 

Thanks!

**Comment by ChrisRegado** [comment]
Released [v1.2.2](https://github.com/ChrisRegado/streamdeck-googlemeet/releases/tag/v1.2.2).
