### ISSUE TITLE
Make it so disconnected icon can be turned off

### ISSUE THREAD

**Issue by wkeithvan** [ChrisRegado/streamdeck-googlemeet#29]
When I'm not in a meeting, the icons for the mic and camera have the red disconnected icons on top of them. This doesn't look great and I'd love something that is either more subtle (maybe have them greyed out) or the ability in the Stream Deck app to configure if the red icon shows or not.

**Comment by ChrisRegado** [comment]
You can change key icons in the Stream Deck desktop app, so you're able to override the disconnected icons however you wish without any code changes. See https://help.elgato.com/hc/en-us/articles/360028237271-Elgato-Stream-Deck-Customizing-Key-Icons for more info.
<img width="519" alt="icon_selection_screenshot" src="https://user-images.githubusercontent.com/1444732/186291363-2275cba8-fb1c-45c7-8969-d11d560d6c69.png">
