### ISSUE TITLE
Meetings started with Mute On do now show correctly on Streamdeck

### ISSUE THREAD

**Issue by cvanover7** [ChrisRegado/streamdeck-googlemeet#3]
By default, Google Meet mutes all attendees when they join if there are 5 or more participants. In this scenario, the participant is muted, but the StreamDeck is not updated and it shows it as Unmuted even though the actual meeting is muted, resulting in out-of-sync.

**Comment by ChrisRegado** [comment]
This should be fixed as of v1.1.1. If not, please let me know!

**Comment by cvanover7** [comment]
Yes, it worked great, thanks for the quick response. It's a terrific
plug-in.
