### ISSUE TITLE
Add reaction buttons

### ISSUE THREAD

**Issue by msthomaz** [ChrisRegado/streamdeck-googlemeet#32]
![image](https://user-images.githubusercontent.com/1915003/216054011-d6041903-8de2-47bb-84b9-b8501e54816b.png)

Add buttons to reactions emojis

**Comment by wjhrdy** [comment]
This would be amazing

**Comment by ChrisRegado** [comment]
Add by @samjgalbraith in #33. This is now available in [release v1.4.0](https://github.com/ChrisRegado/streamdeck-googlemeet/releases/tag/v1.4.0).
