### ISSUE TITLE
 WebSocket connection to 'ws://127.0.0.1:2394/' failed

### ISSUE THREAD

**Issue by sdk0000** [ChrisRegado/streamdeck-googlemeet#35]
Hello,

I'm having trouble with establishing a WebSocket connection while using the Stream Deck plugin for Google Meet. The error message I am receiving is as follows:

```
stream_deck_connection_manager.js:58 WebSocket connection to 'ws://127.0.0.1:2394/' failed:
```

I've checked to make sure the WebSocket server is running on localhost at port 2394. Here's what I get when I use the `lsof` command:

```
❯ lsof -i :2394
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
main 2293 sdk 8u IPv4 0xba7d0a72edc0a88b 0t0 TCP localhost:ms-olap2 (LISTEN)
```

I've also successfully connected to localhost at port 2394 using telnet:
```
telnet 127.0.0.1 2394

Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

his suggests that the WebSocket server is indeed running and that the port is accessible. However, the connection still fails when it's established by the Stream Deck plugin. I've checked for potential firewall issues, but I didn't find anything that would block this connection.

Any help or suggestions would be greatly appreciated. Thank you.

**Comment by ChrisRegado** [comment]
Do you have any sort of adblocker or content blocker running in your browser (e.g. uBlock Origin)? They often block connections to localhost. If so, adding meet.google.com as a trusted site in the blocker's settings should get it working.

**Comment by sdk0000** [comment]
I use Brave browser. Brave blocks ads by default. Your statement was correct; it is currently functioning normally. Thank you for your support.

**Comment by MrTomek** [comment]
add to custom filter to ublick or brave

```
@@127.0.0.1:2394^
```
