### ISSUE TITLE
Manifest file is missing or unreadable on setup

### ISSUE THREAD

**Issue by jeffbulltech** [ChrisRegado/streamdeck-googlemeet#50]
When clicking the "load unpacked" option in Google Chrome I get the following error (see attached).
![streamdeck_google_meet_error](https://github.com/user-attachments/assets/44526f13-e8de-47bf-ad5c-ec63e6d17734)

**Comment by ChrisRegado** [comment]
Is `~/Documents/streamdeck-googlemeet-1.5.0` the whole git repo or just the browser extension? The folder that needs to be opened is the `browser-extension` folder within the repo, i.e. `~/Documents/streamdeck-googlemeet-1.5.0/browser-extension`
