### ISSUE TITLE
Does not work with another google user

### ISSUE THREAD

**Issue by roukmoute** [ChrisRegado/streamdeck-googlemeet#6]
Hi,

It works very well with my main user.  
But when I connect to another user on my google meet, it does not work at all.

Do you have any idea for that?

**Comment by ChrisRegado** [comment]
Hi @roukmoute,

There shouldn't be any problems with using multiple Google accounts.

1. Is your secondary user account set to a language other than English by any chance? 
2. In your browser console, are there any errors that appear during calls? Particularly when you try to mute/unmute via the web UI or Stream Deck buttons? (If you're not familiar with how to check this, please follow the instructions from https://github.com/ChrisRegado/streamdeck-googlemeet/issues/5 to create and upload logs.)

**Comment by roukmoute** [comment]
OK this is the language!
I'm french and my secondary account is set in French.

I've switched here: https://myaccount.google.com/u/1/language

**Comment by ChrisRegado** [comment]
Quick update here. As of [release v1.2.0](https://github.com/ChrisRegado/streamdeck-googlemeet/releases/tag/v1.2.0), all buttons except the new Raise/Lower Hand button should work in any language.
